### PR TITLE
Work on rewrite of Seattle pattern

### PR DESCRIPTION
**Pull request by ianzd**

### CODE REVIEW

**Comment by bri-meow** [comment]
plz to be providing a description with all of your pull requests.  emojis preferred.
:pizza :cake :cactus

**Comment by bri-meow** [comment]
EMOJI FAIL BRO

:pizza: :cake: :cactus:

**Comment by ianzd** [comment]
:apple :monkey :carburetor

**Comment by ianzd** [comment]
:apple:  :monkey:  :carburetor:

**Pull request merged**
